
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: machines.naglfar.pingcap.com
spec:
  group: naglfar.pingcap.com
  names:
    kind: Machine
    listKind: MachineList
    plural: machines
    singular: machine
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Machine is the Schema for the machines API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MachineSpec defines the desired state of Machine
          properties:
            dockerPort:
              description: default 2375 (unencrypted) or 2376(encrypted)
              minimum: 0
              type: integer
            dockerTLS:
              description: default false
              type: boolean
            dockerVersion:
              type: string
            exclusiveDisks:
              items:
                type: string
              type: array
            host:
              type: string
            reserve:
              properties:
                cores:
                  description: default 1
                  format: int32
                  type: integer
                memory:
                  description: default 1 GiB
                  type: string
              type: object
            timeout:
              description: default 10s
              type: string
          required:
          - host
          type: object
        status:
          description: MachineStatus defines the observed state of Machine
          properties:
            info:
              properties:
                architecture:
                  type: string
                devices:
                  additionalProperties:
                    properties:
                      filesystem:
                        type: string
                      mountPoint:
                        type: string
                      total:
                        type: string
                      used:
                        type: string
                    required:
                    - filesystem
                    - mountPoint
                    - total
                    - used
                    type: object
                  type: object
                hostname:
                  type: string
                memory:
                  type: string
                threads:
                  format: int32
                  type: integer
              required:
              - architecture
              - hostname
              - memory
              - threads
              type: object
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
