
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: testresources.naglfar.pingcap.com
spec:
  group: naglfar.pingcap.com
  names:
    kind: TestResource
    listKind: TestResourceList
    plural: testresources
    singular: testresource
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: TestResource is the Schema for the testresources API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TestResourceSpec defines the desired state of TestResource
          properties:
            cpuPercent:
              format: int32
              type: integer
            disks:
              items:
                properties:
                  kind:
                    enum:
                    - nvme
                    - other
                    type: string
                  mountPath:
                    type: string
                  name:
                    type: string
                  size:
                    format: int64
                    type: integer
                required:
                - kind
                - mountPath
                - name
                - size
                type: object
              type: array
            memory:
              format: int64
              type: integer
            testMachineResource:
              description: If sets, it means the static machine is required
              type: string
          required:
          - cpuPercent
          - memory
          type: object
        status:
          description: TestResourceStatus defines the observed state of TestResource
          properties:
            clusterIP:
              description: ClusterIP is the ip address of the container in the overlay(or
                calico) network
              type: string
            diskStat:
              items:
                properties:
                  kind:
                    enum:
                    - nvme
                    - other
                    type: string
                  mountPath:
                    type: string
                  path:
                    type: string
                  size:
                    format: int64
                    type: integer
                required:
                - kind
                - mountPath
                - path
                - size
                type: object
              type: array
            hostMachine:
              type: string
            initialized:
              type: boolean
            password:
              type: string
            sshPort:
              type: integer
            username:
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
