
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: testworkflows.naglfar.pingcap.com
spec:
  group: naglfar.pingcap.com
  names:
    kind: TestWorkflow
    listKind: TestWorkflowList
    plural: testworkflows
    singular: testworkflow
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: TestWorkflow is the Schema for the testworkflows API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TestWorkflowSpec defines the desired state of TestWorkflow
          properties:
            steps:
              items:
                properties:
                  name:
                    type: string
                  testClusterTopology:
                    description: TestClusterTopology is the Schema for the testclustertopologies
                      API
                    properties:
                      apiVersion:
                        description: 'APIVersion defines the versioned schema of this
                          representation of an object. Servers should convert recognized
                          schemas to the latest internal value, and may reject unrecognized
                          values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                        type: string
                      kind:
                        description: 'Kind is a string value representing the REST
                          resource this object represents. Servers may infer this
                          from the endpoint the client submits requests to. Cannot
                          be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                        type: string
                      metadata:
                        type: object
                      spec:
                        description: TestClusterTopologySpec defines the desired state
                          of TestClusterTopology
                        properties:
                          resourceRequest:
                            type: string
                          tidbCluster:
                            properties:
                              monitor:
                                items:
                                  type: string
                                type: array
                              pd:
                                items:
                                  type: string
                                type: array
                              tidb:
                                items:
                                  type: string
                                type: array
                              tikv:
                                items:
                                  type: string
                                type: array
                            type: object
                          type:
                            enum:
                            - tidb-cluster
                            type: string
                        required:
                        - type
                        type: object
                      status:
                        description: TestClusterTopologyStatus defines the observed
                          state of TestClusterTopology
                        properties:
                          state:
                            description: default Pending
                            enum:
                            - Pending
                            - Ready
                            type: string
                        type: object
                    type: object
                  testResourceRequest:
                    description: TestResourceSpec defines the desired state of TestResource
                    properties:
                      cpuPercent:
                        format: int32
                        type: integer
                      disks:
                        items:
                          properties:
                            kind:
                              enum:
                              - nvme
                              - other
                              type: string
                            mountPath:
                              type: string
                            name:
                              type: string
                            size:
                              format: int64
                              type: integer
                          required:
                          - name
                          type: object
                        type: array
                      machineSelector:
                        type: string
                      memory:
                        format: int64
                        type: integer
                    required:
                    - cpuPercent
                    - memory
                    type: object
                  testWorkload:
                    description: TestWorkload is the Schema for the testworkloads
                      API
                    properties:
                      apiVersion:
                        description: 'APIVersion defines the versioned schema of this
                          representation of an object. Servers should convert recognized
                          schemas to the latest internal value, and may reject unrecognized
                          values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                        type: string
                      kind:
                        description: 'Kind is a string value representing the REST
                          resource this object represents. Servers may infer this
                          from the endpoint the client submits requests to. Cannot
                          be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                        type: string
                      metadata:
                        type: object
                      spec:
                        description: TestWorkloadSpec defines the desired state of
                          TestWorkload
                        properties:
                          clusterTopologies:
                            description: ClusterTopologiesRefs references
                            items:
                              properties:
                                aliasName:
                                  type: string
                                name:
                                  type: string
                              required:
                              - aliasName
                              - name
                              type: object
                            type: array
                          teardownTestClusterTopology:
                            items:
                              type: string
                            type: array
                          workloads:
                            description: Workloads specifies workload templates
                            items:
                              properties:
                                dockerContainer:
                                  properties:
                                    command:
                                      items:
                                        type: string
                                      type: array
                                    image:
                                      type: string
                                    name:
                                      type: string
                                    resourceRequest:
                                      properties:
                                        name:
                                          type: string
                                        node:
                                          type: string
                                      required:
                                      - name
                                      - node
                                      type: object
                                  required:
                                  - image
                                  - name
                                  - resourceRequest
                                  type: object
                                name:
                                  type: string
                              required:
                              - name
                              type: object
                            type: array
                        required:
                        - workloads
                        type: object
                      status:
                        description: TestWorkloadStatus defines the observed state
                          of TestWorkload
                        type: object
                    type: object
                required:
                - name
                type: object
              type: array
          type: object
        status:
          description: TestWorkflowStatus defines the observed state of TestWorkflow
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
